name: Run clang-format
description: Runs clang-format and checks for any changes introduced by it
inputs:
  failCondition:
    description: Should checks result in error response
    required: false
    default: 'never'
  workingDirectory:
    description: Working directory for checks
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Check Runner Operating System 🏃‍♂️
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        : Check Runner Operating System 🏃‍♂️
        echo "::notice::run-clang-format action requires a macOS- or Linux-based runner."; exit 2
    - name: Install Dependencies
      if: ${{ runner.os == 'linux' }}
      run: |
        : Install Dependencies
        echo ::group::Install Dependencies
        brew install --quiet zsh
        echo ::endgroup::
      shell: bash
    - run: |
        : clang-format
        if [[ ${GITHUB_EVENT_NAME} == 'pull_request' ]] {
          local -a changes=($(git diff --name-only origin/"${GITHUB_BASE_REF}" HEAD))
        } else {
          local -a changes=($(git diff --name-only HEAD^1 HEAD))
        }
        if (( ${changes[(I)(*.c|*.h|*.cpp|*.hpp|*.m|*.mm)]} )) {
          echo ::group::Install clang-format-13
          brew install --quiet obsproject/tools/clang-format@13
          echo ::endgroup::
          echo ::group::Run clang-format-13
          ./.github/scripts/run-clang-format --fail-${{ inputs.failCondition }} --check
          echo ::endgroup::
        }
        echo "Pass :white_check_mark:" >> $GITHUB_STEP_SUMMARY
      id: result
      name: run-clang-format
      shell: zsh {0}
      working-directory: ${{ github.workspace }}
