name: Dispatch
run-name: Dispatched Repository Actions - ${{ inputs.job }} ⌛️
on:
  workflow_dispatch:
    inputs:
      job:
        description: Dispatch job to run
        required: true
        type: choice
        options:
          - build
permissions:
  contents: write
concurrency:
  group: '${{ github.workflow }}-${{ inputs.job }} @ ${{ inputs.ref || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  check-and-build:
    if: ${{ inputs.job == 'build' }}
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
